### ISSUE TITLE
does not build on Ubuntu 22.04

### ISSUE THREAD

**Issue by beattie** [mangopi-sbc/buildroot-mangopi-r#2]
First failure is fixed by patching m4. but then host-fakeroot fails

**Comment by nemesis5324** [comment]
My error is:
```console
libfakeroot.c:99:40: error: ‘_STAT_VER’ undeclared (first use in this function)
   99 | #define INT_NEXT_STAT(a,b) NEXT_STAT64(_STAT_VER,a,b)
```

I fixed it by adding following lines to `libfakeroot.c`:
```console
#ifndef _STAT_VER
#define _STAT_VER 0
#endif
```
